In [184]:
# Importing libraries.
import pandas as pd
import matplotlib.pyplot as plt

In [185]:
# Read the datasets
dataset = pd.read_csv("aqardata.csv")

In [186]:
print("Old shape  : " , dataset.shape)
dataset = dataset.dropna()
print("Dataset new shape after dropping null values :" , dataset.shape)
dataset.head(50)

Old shape  :  (2951, 8)
Dataset new shape after dropping null values : (2031, 8)


mainlocation  sublocation      neighborhood   frontage        purpose  \
0         الرياض   غرب الرياض       حي ظهرة لبن       شمال           سكني   
5         الرياض  شمال الرياض         حي العارض       جنوب          تجاري   
6            جدة     شمال جدة         حي الريان        شرق           سكني   
11        الرياض  جنوب الرياض          حي السلي    3 شوارع          تجاري   
12        الرياض   شرق الرياض        حي اشبيلية  شمال غربي           سكني   
13           جدة     شمال جدة        حي الزهراء       جنوب           سكني   
15        الرياض   شرق الرياض          حي الشرق       شمال           سكني   
18        الرياض  شمال الرياض       حي القيروان    4 شوارع          تجاري   
20        الرياض  شمال الرياض         حي النرجس        شرق           سكني   
21        الرياض  شمال الرياض     حي صلاح الدين    3 شوارع          تجاري   
24           جدة     شمال جدة         حي الورود        غرب  سكني أو تجاري   
27        الرياض  شمال الرياض         حي النرجس        شرق           سكني   
30        الرياض  جنوب الرياض        حي المشاعل    3 شوارع          تجاري   
32        الرياض  جنوب الرياض       حي الغنامية        غرب           سكني   
37        الرياض  شمال الرياض          حي بنبان    4 شوارع  سكني أو تجاري   
45        الرياض   شرق الرياض         حي الرمال    3 شوارع  سكني أو تجاري   
46        الرياض   شرق الرياض         حي الخليج    3 شوارع           سكني   
47        الرياض  جنوب الرياض        حي المشاعل    3 شوارع          تجاري   
54        الرياض   غرب الرياض           حي عرقة        شرق           سكني   
55        الرياض   شرق الرياض          حي الملز    4 شوارع  سكني أو تجاري   
59        الرياض   شرق الرياض        حي الحمراء       شمال           سكني   
61        الرياض   غرب الرياض           حي طويق       جنوب          تجاري   
65        الرياض   غرب الرياض       حي ظهرة لبن       جنوب           سكني   
67        الرياض   غرب الرياض     حي ضاحية نمار       جنوب           سكني   
69           جدة     شمال جدة       حي الصالحية        غرب           سكني   
70        الرياض  جنوب الرياض        حي المصفاة       شمال          تجاري   
71        الرياض  شمال الرياض          حي الندى        شرق           سكني   
75        الرياض  جنوب الرياض  حي الدار البيضاء  شمال شرقي  سكني أو تجاري   
76           جدة     شمال جدة        حي الياقوت       شمال           سكني   
79        الرياض   غرب الرياض        حي الخزامى        شرق           سكني   
80        الرياض  شمال الرياض          حي بنبان       شمال           سكني   
81           جدة     شمال جدة         حي الرياض        شرق  سكني أو تجاري   
82        الرياض   شرق الرياض       حي القادسية       شمال           سكني   
85        الرياض  شمال الرياض           حي حطين  جنوب شرقي           سكني   
87        الرياض   شرق الرياض        حي اليرموك        شرق  سكني أو تجاري   
89        الرياض  شمال الرياض         حي الملقا  شمال غربي           سكني   
90        الرياض  شمال الرياض         حي الملقا    4 شوارع          تجاري   
91        الرياض  شمال الرياض        حي الصحافة  شمال غربي           سكني   
93        الرياض   غرب الرياض           حي عرقة       شمال           سكني   
94        الرياض   شرق الرياض       حي القادسية       جنوب           سكني   
96        الرياض   غرب الرياض           حي عرقة  شمال شرقي           سكني   
97        الرياض   غرب الرياض           حي عرقة  شمال شرقي           سكني   
98        الرياض  شمال الرياض         حي النرجس        شرق           سكني   
99        الرياض  شمال الرياض         حي الملقا  جنوب شرقي           سكني   
100       الرياض  شمال الرياض       حي الياسمين       جنوب  سكني أو تجاري   
101       الرياض   شرق الرياض       حي المونسية       جنوب           سكني   
102       الرياض  شمال الرياض          حي الندى        شرق           سكني   
103       الرياض  شمال الرياض         حي النرجس       شمال          تجاري   
105       الرياض   غرب الرياض           حي عرقة        غرب           سكني   
107       الرياض  شمال الرياض           حي حطين        شرق           سكني   

     streetwidth     size  Pricepm  
0           20.0      727     1800  
5 

In [187]:
#converting clumns to numericals manualy
#dataset = dataset.drop('neighborhood', axis='columns')
dataset['mainlocation'].replace({'الرياض': 0, 'جدة': 1},inplace = True)
dataset['purpose'].replace({'سكني': 0, 'تجاري': 1 , 'سكني أو تجاري':2  , 'غير محدد':3},inplace = True)
dataset['sublocation'].replace({'وسط الرياض': 0, 'غرب الرياض': 1 , 'شمال الرياض':2 , 'شرق الرياض':3 , 'جنوب الرياض':4 , 'شمال جدة':5 , 'جنوب جدة':6},inplace = True)
dataset['frontage'].replace({'غرب': 0, 'شمال': 1 , 'شرق':2 , 'جنوب':3 , 'شمال غربي':4 , 'شمال شرقي':5 , 'جنوب غربي':6 , 'جنوب شرقي':7 , '4 شوارع':8 , '3 شوارع':9},inplace = True)
    

# using .get_dummies function to convert the categorical datatype to numerical and storing the returned dataFrame in a new variable df1
df1 = pd.get_dummies(dataset['neighborhood'])
# using pd.concat to concatenate the dataframes df and df1 and storing the concatenated dataFrame in df.
dataset = pd.concat([dataset , df1], axis=1).reindex(dataset.index)
# removing the column 'Purchased' from df as it is of no use now.
dataset.drop('neighborhood' , axis = 1 , inplace=True)

# Moving the target column (Pricepm) to the last
column_to_move = dataset.pop("Pricepm")
dataset.insert(142, "Pricepm", column_to_move)
    
# printing results
print("Dataset's new shape : " , dataset.shape)
dataset.head(40)

Dataset's new shape :  (2031, 143)


mainlocation  sublocation  frontage  purpose  streetwidth     size  \
0              0            1         1        0         20.0      727   
5              0            2         3        1         60.0     5973   
6              1            5         2        0         20.0      660   
11             0            4         9        1         35.0     3200   
12             0            3         4        0         20.0      743   
13             1            5         3        0         15.0      600   
15             0            3         1        0         25.0      840   
18             0            2         8        1         30.0     3000   
20             0            2         2        0         15.0      525   
21             0            2         9        1         80.0     3250   
24             1            5         0        2         55.0     4160   
27             0            2         2        0         15.0     1050   
30             0            4         9        1         30.0     7222   
32             0            4         0        0         10.0      480   
37             0            2         8        2        100.0  2610000   
45             0            3         9        2         46.0    13200   
46             0            3         9        0         15.0     2560   
47             0            4         9        1         30.0    14570   
54             0            1         2        0         16.0     1200   
55             0            3         8        2         30.0     4980   
59             0            3         1        0         20.0      580   
61             0            1         3        1         60.0      900   
65             0            1         3        0         20.0      450   
67             0            1         3        0         15.0      998   
69             1            5         0        0         16.0      870   
70             0            4         1        1         30.0      750   
71             0            2         2        0         15.0      360   
75             0            4         5        2         36.0     1050   
76             1            5         1        0         32.0      300   
79             0            1         2        0         10.0      400   
80             0            2         1        0         15.0      375   
81             1            5         2        2         35.0      899   
82             0            3         1        0         15.0      325   
85             0            2         7        0         15.0     1575   
87             0            3         2        2         20.0      747   
89             0            2         4        0         20.0      900   
90             0            2         8        1         36.0    21563   
91             0            2         4        0         15.0      300   
93             0            1         1        0         15.0      490   
94             0            3         3        0         25.0      402   

    حي ابحر الجنوبية  حي ابحر الشمالية  حي اشبيلية  حي الازدهار  ...  حي عكاظ  \
0                  0                 0           0            0  ...        0   
5                  0                 0           0            0  ...        0   
6                  0                 0           0            0  ...        0   
11                 0                 0           0            0  ...        0   
12                 0                 0           1            0  ...        0   
13                 0                 0           0            0  ...        0   
15                 0                 0           0            0  ...        0   
18                 0                 0           0            0  ...        0   
20                 0                 0           0            0  ...        0   
21                 0                 0           0            0  ...        0   
24                 0                 0           0            0  ...        0 

In [188]:
#separating the dependent and independent values....

#X-Independent variable
X = dataset.iloc[ : , 0:141 ].values
print(X)

#y-dependent or target variable
y = dataset.iloc[ : , 142 ].values
print('\n',y)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 2. 3. ... 0. 0. 0.]
 [1. 5. 2. ... 0. 0. 0.]
 ...
 [1. 5. 9. ... 0. 0. 0.]
 [0. 4. 4. ... 0. 0. 0.]
 [0. 2. 3. ... 0. 0. 0.]]

 [1800 2000 2300 ... 2777 1200 2900]


In [217]:
# SVC model 
#Mean Absolute Error: 1186.33 +/- 43.59
#Root Mean Squared Error: 2265.35 +/- 985.48
#R-squared: -0.05 +/- 0.05
from sklearn.svm import SVC
model = SVC()

In [197]:
#linear regression model
#Mean Absolute Error: 678.72 +/- 107.20
#Root Mean Squared Error: 2522.63 +/- 1271.64
#R-squared: -0.84 +/- 2.05
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [205]:
#gradient boosting classifier model
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()

In [ ]:
#logistic regression model (Didn't work)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 2000)

In [195]:
#naive bayes model
#Mean Absolute Error: 1732.39 +/- 136.76
#Root Mean Squared Error: 3056.03 +/- 1110.78
#R-squared: -1.09 +/- 0.72
from sklearn.naive_bayes import GaussianNB

# Build a Gaussian Classifier
model = GaussianNB()

In [162]:
#neural network (Didn't work)
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(max_iter = 1500)

In [90]:
#RandomForestClassifier model
#Mean Absolute Error: 986.17 +/- 43.47
#Root Mean Squared Error: 2168.22 +/- 946.92
#R-squared: 0.04 +/- 0.08
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [191]:
# Lasso
#Mean Absolute Error: 667.34 +/- 89.68
#Root Mean Squared Error: 2482.75 +/- 1238.11
#R-squared: -0.74 +/- 1.90
from sklearn.linear_model import Lasso
model = Lasso()

In [214]:
# Decision tree model
#Mean Absolute Error: 652.28 +/- 83.55
#Root Mean Squared Error: 2565.64 +/- 1319.01
#R-squared: -0.55 +/- 1.22
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [212]:
# KNN
#Mean Absolute Error: 1087.95 +/- 24.91
#Root Mean Squared Error: 2267.57 +/- 1021.46
#R-squared: -0.04 +/- 0.05
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 18)

In [208]:
#GradientBoostingRegressor
#Mean Absolute Error: 694.81 +/- 62.65
#Root Mean Squared Error: 2812.83 +/- 1406.41
#R-squared: -1.21 +/- 2.07
from sklearn import ensemble
model = ensemble.GradientBoostingRegressor()

In [210]:
# ExtraTrees
#Mean Absolute Error: 559.20 +/- 57.24
#Root Mean Squared Error: 3046.20 +/- 1252.41
#R-squared: -1.62 +/- 2.20
from sklearn.ensemble import ExtraTreesRegressor
model = ExtraTreesRegressor()

In [218]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Define the number of folds for cross-validation
kf = KFold(n_splits = 5 , shuffle = True , random_state = 93)

# Initialize arrays to store metrics for each fold
mae_scores = []
rmse_scores = []
r2_scores = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(X):
    # Split the dataset into training and testing sets for this fold
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Fit the model on the training set
    model.fit(X_train, y_train)
    
    # Make predictions on the testing set
    y_pred = model.predict(X_test)
    
    # Calculate the MAE, RMSE, and R2 scores for this fold
    fold_mae = mean_absolute_error(y_test, y_pred)
    fold_rmse = mean_squared_error(y_test, y_pred, squared=False)
    fold_r2 = r2_score(y_test, y_pred)
    
    # Append the scores to the arrays
    mae_scores.append(fold_mae)
    rmse_scores.append(fold_rmse)
    r2_scores.append(fold_r2)

# Calculate the mean and standard deviation of the scores across all folds
mean_mae = np.mean(mae_scores)
std_mae = np.std(mae_scores)
mean_rmse = np.mean(rmse_scores)
std_rmse = np.std(rmse_scores)
mean_r2 = np.mean(r2_scores)
std_r2 = np.std(r2_scores)

# Print the results
print("Mean Absolute Error: {:.2f} +/- {:.2f}".format(mean_mae, std_mae))
print("Root Mean Squared Error: {:.2f} +/- {:.2f}".format(mean_rmse, std_rmse))
print("R-squared: {:.2f} +/- {:.2f}".format(mean_r2, std_r2))
print(r2_scores)

Mean Absolute Error: 1436.16 +/- 10.78
Root Mean Squared Error: 2453.49 +/- 923.74
R-squared: -0.28 +/- 0.15
[-0.39260121292127836, -0.21395103600944654, -0.2696343468151392, -0.4779566059018119, -0.03982251528443426]
